language: php
sudo: required

services:
  - docker

script:
  - docker build --pull --no-cache -t mistermatt/mattermost-slash:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ];
    then docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
    docker push mistermatt/mattermost-slash:latest; fi
