language:

sudo: required

services:
  - docker

script:
  - docker build --pull --no-cache -t mistermatt/mattermost-slash:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ];
    then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    docker push mistermatt/mattermost-slash:latest; fi
